services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bayrktlihn
      POSTGRES_USER: bayrktlihn
      POSTGRES_DB: bayrktlihn